- name: Create Directory Sosmed
  file:
     path: /var/www/html/landingpage
     mode: 0775
     state: directory
     state: absent

- name: Clone Landingpage
  git:
     repo: https://github.com/rizdinahmad/landingpage.git
     dest: /var/www/html/landingpage

- name: Copy File Conf Nginx-landingpage
  template:
     src: templates/landingpage.conf.j2
     dest: /etc/nginx/sites-enabled/landingpage.conf
  notify:
     - Restart Nginx

- name: Restart Nginx
  service:
     name: nginx
     state: restarted
