- name: Install Web Server Nginx-Ubuntu
  apt:
     name: nginx
     state: present    

#- name: Start nginx
#  service:
#    name: nginx
#    state: started

- name: Install Git
  become: true
  apt:
     name: git
     state: latest
